/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demo.api.db.users;


import co.aisystem.demo.api.db.users.tables.Address;
import co.aisystem.demo.api.db.users.tables.Person;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1319335969;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = co.aisystem.demo.api.db.users.tables.Address.ADDRESS;

    /**
     * The table <code>public.person</code>.
     */
    public final Person PERSON = co.aisystem.demo.api.db.users.tables.Person.PERSON;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Person.PERSON);
    }
}
