/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demo.api.db.users;


import co.aisystem.demo.api.db.users.routines.DemographicTableRange;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.lambda.tuple.Range;


/**
 * Convenience access to all stored procedures and functions in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.demographic_table_range</code>
     */
    public static Range<Integer> demographicTableRange(Configuration configuration) {
        DemographicTableRange f = new DemographicTableRange();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.demographic_table_range</code> as a field.
     */
    public static Field<Range<Integer>> demographicTableRange() {
        DemographicTableRange f = new DemographicTableRange();

        return f.asField();
    }
}
