/*
 * This file is generated by jOOQ.
*/
package co.aisystem.demo.api.db.users;


import co.aisystem.demo.api.db.users.tables.Address;
import co.aisystem.demo.api.db.users.tables.Person;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = co.aisystem.demo.api.db.users.tables.Address.ADDRESS;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = co.aisystem.demo.api.db.users.tables.Person.PERSON;
}
